server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/iot_dev
    username: iot
    password: iot
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
