server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/iot_dev
    username: iot
    password: iot
    # aide Spring si besoin (optionnel mais utile quand il "n'infère" pas le driver)
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
